export const FETCH_DISPLAY = 'FETCH_DISPLAY';
export const FETCH_ERROR = 'FETCH_ERROR';

export const FETCH_DISPLAY_LIST = 'FETCH_DISPLAY_LIST';
export const FETCH_REQ_LIST = 'FETCH_REQ_LIST';
export const FETCH_ERROR_LIST = 'FETCH_ERROR_LIST';

export const FETCH_DISPLAY_ALL_LIST = 'FETCH_DISPLAY_ALL_LIST';
export const FETCH_REQ_ALL_LIST = 'FETCH_REQ_ALL_LIST';
export const FETCH_ERROR_ALL_LIST = 'FETCH_ERROR_ALL_LIST';

export const PERSIST_MOVIE_SUCCESS = 'PERSIST_MOVIE_SUCCESS';
export const PERSIST_MOVIE_REQ = 'PERSIST_MOVIE_REQ';
export const PERSIST_MOVIE_REMOVE = 'PERSIST_MOVIE_REMOVE';

export const FIRST_SAGA = 'FIRST_SAGA';



